### PR TITLE
fix: make secretRef configurable and backwards-compatible

### LINKED ISSUE #104: flux_sync: SecretRef should not be the same as resource name
In certain scenario, you would not expect the SecretRef (ssh key) to be the same as the name of the git repository. I don't know if this was chosen by design, but if that's the case it would be better to make it clear in the doc that it will set the same name for the following items:

- GitRepository Resource
    - name
    - secretRef
- Kustomization Resource
    - name

### PR DESCRIPTION
**Pull request by moolen**
This PR makes the `GitRepsository.spec.secretRef` configurable and ensures that the provider stays backwards compatible with the versions pre v0.0.13. 
In 0.0.13 the default secret-name is `flux-system`, before that it was the flux_sync resource name. Details in #104.

Closes #104

### CODE REVIEW

File: pkg/provider/data_sync.go [hunk 1]
```diff
@@ -64,6 +64,12 @@ func DataSync() *schema.Resource {
 				Optional:    true,
 				Default:     syncDefaults.Branch,
 			},
+			"secret": {
+				Description: "The name of the secret that is referenced by GitRepository as SecretRef.",
+				Type:        schema.TypeString,
+				Optional:    true,
+				Computed:    true,
```
Comment (phillebaba) [inline pkg/provider/data_sync.go:71]: I would ranter have that we stick to using the option defaults rather than making this a computed value.

File: pkg/provider/data_sync.go [hunk 2]
```diff
@@ -115,6 +121,12 @@ func dataSyncRead(ctx context.Context, d *schema.ResourceData, m interface{}) di
 	opt.Branch = d.Get("branch").(string)
 	opt.TargetPath = d.Get("target_path").(string)
 	opt.GitImplementation = d.Get("git_implementation").(string)
+	opt.Secret = d.Get("secret").(string)
+	// See #104: fallback to resource name
+	if opt.Secret == "" {
+		opt.Secret = opt.Name
+		d.Set("secret", opt.Name)
+	}
```
Comment (phillebaba) [inline pkg/provider/data_sync.go:129]: I understand that there is a will to keep things backwards compatible, but what are the effects on end users when the secret is replaced as they upgrade from one version of the provider to another?

**Review by phillebaba — APPROVED** [review]

File: pkg/provider/data_sync.go (hunk 1 above)
Comment (moolen) [reply pkg/provider/data_sync.go:71]: I see, that was also my first idea. (more on the compat issue below)

File: pkg/provider/data_sync.go (hunk 2 above)
Comment (moolen) [reply pkg/provider/data_sync.go:129]: For me, personally, backwards-compatibility is important - that's why i proposed the change as it is. If a user upgrades to 0.0.13 the secretRef is wrong users can't sync their repositories: There's no Ops in GitOps happening.
Right now there's nothing that a user can do about it other than creating a secret with the specific name `flux-system`. 

```tf
# example from the readme
resource "kubernetes_secret" "main" {
  metadata {
    name      = data.flux_sync.main.name # <-- this won't work any more.
  }

  data = {
    username = "git"
    password = "1234"
  }
}
```


We can certainly live with a backwards-incompatible change and do the change in our wrapper module. However i sense that we're not the only user of this tf provider.

Certainly, this is a very young project and there's AFAIK no compatibility guarantee. Let me know how you prioritize backwards-compat vs. pretty&simple code, i'll do the changes accordingly. The essential part is to make the `secret` name configurable.

Comment (phillebaba) [reply pkg/provider/data_sync.go:129]: I would rather not implement this special case, as it will probably introduce problems in the future when changes are made again and this special case is removed.

So this will be a breaking change to people who set the name in `data_sync` to something other than the default value and expect the secret to follow along with the same name. I do not know how other people are using the provider but is the majority changing this value? Considering the fact that this issue made its way into 0.13 sadly the harm is to a certain degree already done. I totally agree with you that getting secret ref in should be done ASAP, I will create a release as soon as we merge this. 

After thinking about this during the weekend I think we should stick with using the default values set by default options in the fluxv2 repo. If you can make those changes I will merge this PR.

Comment (moolen) [reply pkg/provider/data_sync.go]: sure, that works!

**Comment by moolen** [comment]
There's an outage with github actions right now [link](https://www.githubstatus.com/incidents/s654n76c1bwr). I'll check back tomorrow to see if i need to re-trigger ci

**Review by phillebaba — APPROVED** [review]
LGTM :rose: 

Thank you for the hard work. I just need to merge a couple of other PRs so will make a release later tonight.
