### PR TITLE
Validate kubeconfig during provider configuration.

### LINKED ISSUE #656: [Bug]: validate kubernetes credential on every plan/apply
### Describe the bug

I find that terraform-provider-flux doesn't check the validity of kubernetes credential on every `terraform plan`/`terraform apply`. So invalid kubernetes credentials could stay undetected in terraform-provider-flux for a long time and breaking in a fresh bootstrap.

### Steps to reproduce

1. Bootstrap a testing cluster with the following provider configuration
```terraform
provider "flux" {
  kubernetes = {
    config_path     = "~/.kube/config"
  }
  git = {}
}
```

2. Refactor the kubernetes credential configuration:
```terraform
provider "flux" {
  kubernetes = {
    config_path     = "~/.kube/non_existed_config"
  }
  git = {}
}
```

Or the following example based on a real refactor regression:
```terraform
provider "flux" {
  kubernetes = {
    client_certificate     = var.KUBE_CLIENT_CERT_DATA
    config_path            = var.KUBE_CLIENT_KEY_DATA // The config_path should be client_key
    cluster_ca_certificate = var.KUBE_CLUSTER_CA_CERT_DATA
    host                   = var.KUBE_HOST
  }
  git = {}
}
```

3. Running `terraform plan` or `terraform apply` won't detect the kubernetes credential handling is problematic.

### Expected behavior

validate kubernetes credential on every plan/apply phase

### Screenshots and recordings

_No response_

### Terraform and provider versions

OpenTofu v1.6.2
on linux_amd64
+ provider registry.opentofu.org/fluxcd/flux v1.2.3

### Terraform provider configurations

provider "flux" {
  kubernetes = {
    config_path     = "~/.kube/non_existed_config"
  }
  git = {}
}

### flux_bootstrap_git resource

resource "flux_bootstrap_git" "fleet" {
  cluster_domain = var.cluster_domain
  path           = var.watch_path
}

### Flux version

null

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by swade1987**
## Description
Validate kubernetes connectivity during provider configuration to reduce errors later on.

## Motivation and Context
Fixes #656

## How has this been tested?
- [x] Have you added an acceptance test for the functionality being added?
- [x] Have you run the acceptance tests on this branch?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation
- [x] I have updated the documentation (if required) with `make docs`

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/fluxcd/terraform-provider-flux/blob/main/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

## Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

**Comment by networkhermit** [comment]
I notice that the validate logic triggers a ServiceAccountList request in default namespace. I don't know, but is it possible for it to get reported and marked by some audit framework? If that's the case, ServiceList or else would be more harmless candidate. (Correct me if it's just me being over cautious.)

File: internal/provider/provider.go [hunk 1]
```diff
@@ -377,6 +380,23 @@ func (p *fluxProvider) Configure(ctx context.Context, req provider.ConfigureRequ
...
+	// ================================================
+	// Validate kubernetes connectivity
+	// ================================================
+	kubeClient, err := prd.GetKubernetesClient()
+	if err != nil {
+		resp.Diagnostics.AddError("Could not create Kubernetes client", err.Error())
+		return
+	}
+
+	var list corev1.ServiceAccountList
```
Comment (stefanprodan) [inline internal/provider/provider.go:393]:
```suggestion
	var list apiextensionsv1.CustomResourceDefinitionList
```

Using this import `apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"`

This is what we do in the Flux CLI, which also verifies that the kubeconfig user has cluster-wide access which is required to install Flux.

Comment (swade1987) [reply internal/provider/provider.go:393]: @stefanprodan Is there a better way for me to use flux to verify connectivity?

Comment (stefanprodan) [reply internal/provider/provider.go:393]: The code I suggest should be enough for validating both the  connectivity and permissions.

File: internal/provider/provider.go [hunk 2]
```diff
@@ -377,6 +380,23 @@ func (p *fluxProvider) Configure(ctx context.Context, req provider.ConfigureRequ
 		resp.Diagnostics.AddError("Could not create provider resource data", err.Error())
 		return
 	}
+
+	// ================================================
+	// Validate kubernetes connectivity
```
Comment (stefanprodan) [inline internal/provider/provider.go:385]:
```suggestion
	// Validate Kubernetes API connectivity and kubeconfig permissions 
```

File: internal/provider/provider.go [hunk 3]
```diff
@@ -377,6 +380,23 @@ func (p *fluxProvider) Configure(ctx context.Context, req provider.ConfigureRequ
...
+	// ================================================
+	kubeClient, err := prd.GetKubernetesClient()
+	if err != nil {
+		resp.Diagnostics.AddError("Could not create Kubernetes client", err.Error())
+		return
+	}
+
+	var list apiextensionsv1.CustomResourceDefinitionList
+	selector := client.MatchingLabels{manifestgen.PartOfLabelKey: manifestgen.PartOfLabelValue}
+	if err := kubeClient.List(ctx, &list, client.InNamespace("default"), selector); err != nil {
```
Comment (stefanprodan) [inline internal/provider/provider.go:395]:
```suggestion
	if err := kubeClient.List(ctx, &list, client.InNamespace(""), selector); err != nil {
```

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @swade1987
